# =========================
# Frontend Service

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend

  ports:
    - port: 80
      targetPort: 80

---

# =========================
# Backend Service

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: ${port_back}
      targetPort: ${port_back}
